### ISSUE TITLE
求相关工具箱

### ISSUE THREAD

**Issue by huen77** [liuzhenguo666/Enhancing-Robustness-and-Resilience-of-Multiplex-Networks-Against-Node-Community-Cascading-Failures#1]

**Comment by q-jx** [comment]
博主您好，我也遇到了decode_mod函数没找到的问题，是否也方便分享一下呢，邮箱1042558753@qq.com,非常感谢！

**Comment by 11111557** [comment]
我同样也遇到了decode_mod函数没找到的问题，我的邮箱yangye@nenu.edu.cn,非常感谢您的分享！

**Comment by 11111557** [comment]
您好，您的文章《Enhancing Robustness and Resilience of Multiplex Networks against Node-community Cascading Failures》中补充文件supplemental items一直下载不下来，请问能邮箱发我一份吗？此外您回复的相关工具箱我没有找到。
期待您的回复！祝您端午节快乐！






发件人：huen77 ***@***.***>
发送日期：2024-06-04 13:40:08
收件人：liuzhenguo666/Enhancing-Robustness-and-Resilience-of-Multiplex-Networks-Against-Node-Community-Cascading-Failures ***@***.***>
抄送人：11111557 ***@***.***>,Comment ***@***.***>
主题：Re: [liuzhenguo666/Enhancing-Robustness-and-Resilience-of-Multiplex-Networks-Against-Node-Community-Cascading-Failures] 求相关工具箱 (Issue #1)

Closed #1 as completed.
